name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    uses: devotica-labs/terraform-shared-config/.github/workflows/terraform-module-release.yml@v1
    with:
      terraform-version: "1.9.5"
    secrets: inherit
